spring:
  application:
    name: orchestrator
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/FREEPDB1
    username: orchestrator
    password: orchestrator123
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
        format_sql: true

scheduler:
  observer:
    fixed-delay: 30000
  order:
    fulfillment-delay: 60000
  lock:
    ttl: 60000
wes:
  api:
    base-url: http://localhost:3678
inventory:
  api:
    base-url: http://localhost:3778
